name: midnight_confessions
description: "A Story-based Dedective Game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # BUNU EKLE
    sdk: flutter
  intl: ^0.20.2 # BUNU EKLE

  # UI & Core
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  equatable: ^2.0.5

  # State Management (BLoC)
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3

  # Code Generation (Annotations)
  # Bu versiyonlar birbiriyle tam uyumlu
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Game Engine
  # Bu versiyonlar da birbiriyle tam uyumlu
  flame: ^1.17.0
  flame_audio: ^2.10.0
  rive: ^0.13.4

  # Widgets
  card_swiper: ^3.0.1
  http: ^1.4.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.0.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation (Runners)
  # Bu versiyonlar da birbiriyle tam uyumlu
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter_native_splash:
  color: "#121212" # Arka plan rengi
  image: assets/images/ui/splash_logo.png # Gösterilecek logo
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ui/app_icon.png"

flutter:
  uses-material-design: true
  generate: true # BUNU EKLE

  assets:
    - assets/cases/
    - assets/images/
    - assets/audio/
    - assets/rive/
    - assets/cases_manifest.json