// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy3zvyUgkAuWuoBHHTnxuRrUpemLh0voM',
    appId: '1:810194845693:web:09a5f09f21951d83742394',
    messagingSenderId: '810194845693',
    projectId: 'midnight-confessions-e68ae',
    authDomain: 'midnight-confessions-e68ae.firebaseapp.com',
    storageBucket: 'midnight-confessions-e68ae.firebasestorage.app',
    measurementId: 'G-JYCP6999CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdJpqP5toEkpyyoxC1uMtYjhp-rkQtPg',
    appId: '1:810194845693:android:4e4947aa499b7538742394',
    messagingSenderId: '810194845693',
    projectId: 'midnight-confessions-e68ae',
    storageBucket: 'midnight-confessions-e68ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOYS4RCYS9x_Ok3YO3knCVN1wHBSOA_ok',
    appId: '1:810194845693:ios:4e15b919cd397c0b742394',
    messagingSenderId: '810194845693',
    projectId: 'midnight-confessions-e68ae',
    storageBucket: 'midnight-confessions-e68ae.firebasestorage.app',
    iosBundleId: 'com.example.midnightConfessions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOYS4RCYS9x_Ok3YO3knCVN1wHBSOA_ok',
    appId: '1:810194845693:ios:4e15b919cd397c0b742394',
    messagingSenderId: '810194845693',
    projectId: 'midnight-confessions-e68ae',
    storageBucket: 'midnight-confessions-e68ae.firebasestorage.app',
    iosBundleId: 'com.example.midnightConfessions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy3zvyUgkAuWuoBHHTnxuRrUpemLh0voM',
    appId: '1:810194845693:web:05f1d416bb88bbaf742394',
    messagingSenderId: '810194845693',
    projectId: 'midnight-confessions-e68ae',
    authDomain: 'midnight-confessions-e68ae.firebaseapp.com',
    storageBucket: 'midnight-confessions-e68ae.firebasestorage.app',
    measurementId: 'G-DLV2YRW2D2',
  );
}
